#!/bin/bash -e
. "$HAM_HOME/bin/ham-bash-setenv.sh"

# NOTE: This is quite slow and should be used only once during setup.
toolset_find_msvc_ide_dir() {
  # We assume that all combinations of visual studio versions and editions
  # can be located in both the x86 and x64 program files directories...
  local vs_pf_dirs=(
    "$PROGRAMW6432\\Microsoft Visual Studio"
    "$PROGRAMFILES\\Microsoft Visual Studio")

  # Version arrays for the different types of visual studio licenses
  # NOTE: the following arrays must be same length
  local vs_versions_typed=(10 2020)
  local vs_versions_typed_prefix=(" " "\\")
  local vs_versions_typed_suffix=(".0" "\\Community")

  # Count of the supported versions / years
  # eg. 2020 all the way to 2025
  # eg. 10.0 all the way to 15.0
  # NOTE: As of early 2023 community version is at 2022 and Visual Studio at 14.0
  local vs_versions_supported_count=6

  # loop through dirs, versions to find the IDE dir
  for vs_pf_dir in "${vs_pf_dirs[@]}"; do
    for i in "${!vs_versions_typed[@]}"; do
      local prefix_=${vs_versions_typed_prefix[$i]}
      local suffix_=${vs_versions_typed_suffix[$i]}
      local version_=${vs_versions_typed[$i]}
      for ((ry = vs_versions_supported_count; ry >= 1; ry--)); do
        local out_version_=$((version_ + ry - 1))
        local out_dir_="${vs_pf_dir}${prefix_}${out_version_}${suffix_}\\Common7\\IDE"
        # echo "D/Checking for IDE dir: ${out_dir_}"
        # We check for the devenv.exe file, because the directory may exist
        # but be empty.
        if [ -d "$out_dir_" ] && [ -f "$out_dir_\\devenv.exe" ]; then
          echo "${out_dir_}"
          return 0
        fi
      done
    done
  done

  ide_dir="c:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/"
  if [ -d "$ide_dir" ] && [ -f "$ide_dir/devenv.exe" ]; then
    echo "${ide_dir}"
    return 0
  fi

  echo ""
}

toolset_find_msvc_ide_dir
