#!/bin/bash
if [ -z "$1" -o -d "$1" ]; then
  DIR="${1:-.}"
  echo "I/Indenting folder '$DIR'"
  find "$DIR" -name "*.hs" -exec echo {} \; -exec hs-indent-file {} \;
else
  # Note: Echo only for debugging since stdout is used as-is in emacs
  # echo "I/Indenting '$1'"
  hs-indent-file "$@"
fi
