#!/bin/bash
if [ "$HAM_BIN_LOA" == "osx-arm64" ]; then
    export PATH="/opt/homebrew/opt/llvm@12/bin:$PATH"
    export LDFLAGS="-L/opt/homebrew/opt/llvm@12/lib"
    export CPPFLAGS="-I/opt/homebrew/opt/llvm@12/include"
    /opt/homebrew/bin/stack --compiler ghc-8.10.7 --system-ghc "$@"
else
    stack "$@"
fi
