#!/bin/bash -e
. ham-bash-lib.sh

export VIRTUAL_ENV_DISABLE_PROMPT=true
unset VIRTUAL_ENV
unset VIRTUAL_ENV_PROMPT

PY3_VENV_BASE_DIR="$(abspath .)"
export PY3_VENV_BASE_DIR
case $HAM_OS in
  NT*)
    export PY3_VENV_BIN_DIR="${PY3_VENV_BASE_DIR}/venv/Scripts"
    ;;
  *)
    export PY3_VENV_BIN_DIR="${PY3_VENV_BASE_DIR}/venv/bin"
    ;;
esac

# Check that the environment is setup
if [ ! -e "${PY3_VENV_BIN_DIR}/activate" ]; then
  PY3_VENV_REQUIREMENTS_SHOULD_INSTALL=yes
  if [ ! -e "py3_requirements.txt" ]; then
    complain "No venv and no py3_requirements.txt present to initialize it. You can use 'echo \"\" > py3_requirements.txt' to initialize an empty one."
    return 1
  fi
  py3-venv "venv"
  if [ ! -e "${PY3_VENV_BIN_DIR}/activate" ]; then
    complain "No '${PY3_VENV_BIN_DIR}/activate' script found after venv activation."
    return 1
  fi
fi

# Pierre: We do the activation ourselves because on Windows the builtin script
# is broken when running in bash. Also its so simple that it really doesn't need
# the potential flakiness.
VIRTUAL_ENV="$(abspath "./venv")"
export VIRTUAL_ENV
export VIRTUAL_ENV_PROMPT="ham-py3-venv"

pathenv_add "$(abspath "${PY3_VENV_BIN_DIR}")"

if [ "$PY3_VENV_REQUIREMENTS_SHOULD_INSTALL" == "yes" ]; then
  # Run requirements-install first so any package versions in the "py3_requirements.txt" lockfile are respected
  py3-venv-requirements-install || return 1
  # Then run pip-reinstall to add any new packages missing from the lockfile, regenerating the lockfile in the process
  py3-venv-pip-reinstall || return 1
  unset PY3_VENV_REQUIREMENTS_SHOULD_INSTALL
fi

EXPECTED_PY3_VER=$(ham-py3 --version)
ACTUAL_PY3_VER=$(python3 --version)
if [ "$EXPECTED_PY3_VER" != "$ACTUAL_PY3_VER" ]; then
  complain "Expected python3 version '$EXPECTED_PY3_VER' but got '$ACTUAL_PY3_VER', please delete the venv directory '$VIRTUAL_ENV' and try again."
  return 1
fi
