#!/bin/bash -e
if [[ -z $HAM_HOME ]]; then
  echo "E/HAM_HOME not set !"
  exit 1
fi
. "$HAM_HOME/bin/ham-bash-setenv.sh"
SCRIPT_DIR=$(path_abs_dirname "${BASH_SOURCE[0]}")
php_run "$SCRIPT_DIR/composer_2.phar" "$@"
