#!/bin/sh
. ham-bash-lib.sh
if [ -e "${1}" ]; then
    XSLTPATH=$1
else
    echo "Can't find XSLT: $1"
    exit 1
fi
if [ -z "$3" ]; then
    OUTPUT=
else
    OUTPUT="--output $3"
fi
# echo "# XSLT1: $2 -> '$(basename ${XSLTPATH})' -> $3"
xslt_tools-xsltproc $OUTPUT $XSLTPATH $2
exit $?
