#!/bin/bash
. ham-bash-lib.sh
args=()
for PARAM in "$@"
do
    if [ "${PARAM:0:1}" == "-" ]; then
        args+=(${PARAM})
    else
        args+=(\"${PARAM}\")
    fi
done
echo xsltproc "${args[@]}" | bash -
exit $?
