#!/bin/sh
. ham-bash-lib.sh
if [ -e "${1}" ]; then
    XSLTPATH=$1
else
    XSLTPATH=`nativedir $AGLDEVENVSRC`/scripts_gen/$1.xslt
fi
if [ -z "$3" ]; then
    OUTPUT=
else
    OUTPUT="--output $3"
fi
# echo "# XSLT1: $2 -> '$(basename ${XSLTPATH})' -> $3"
xslt_tools-xsltproc $OUTPUT $XSLTPATH $2
exit $?
