#!/bin/bash
. ham-bash-lib.sh
export SAXONPATH="${HAM_HOME}/toolsets/xslt_tools/jars/saxon9he.jar"
if [ "$1" == "-version" ]; then
  VERSION=$(java -cp "$SAXONPATH" net.sf.saxon.Transform 2>&1 | grep Saxon)
  if [ -z "$VERSION" ]; then
    echo "E/Can't get Saxon version."
    exit 1
  else
    echo $VERSION
    exit 0
  fi
elif [ -z "$1" ]; then
  # echo "1:" java -cp "$SAXONPATH" net.sf.saxon.Transform
  java -cp "$SAXONPATH" net.sf.saxon.Transform
elif [ -z "$3" ]; then
  # echo "2:" java -cp "$SAXONPATH" net.sf.saxon.Transform -s:"$2" -versionmsg:off -warnings:silent -xsl:"$1"
  java -cp "$SAXONPATH" net.sf.saxon.Transform -s:"$2" -versionmsg:off -warnings:silent -xsl:"$1"
else
  # echo "3:" java -cp "$SAXONPATH" net.sf.saxon.Transform -s:"$2" -versionmsg:off -warnings:silent -xsl:"$1" -o:"$3"
  java -cp "$SAXONPATH" net.sf.saxon.Transform -s:"$2" -versionmsg:off -warnings:silent -xsl:"$1" -o:"$3"
fi
exit $?
