#!/bin/bash -e
. ham-bash-lib.sh

list_files_excluding_aflymake() {
  local dir="$1"

  # List all files
  local files=()
  while IFS= read -r -d '' file; do
    files+=("$file")
  done < <(find "$dir" -maxdepth 1 -type f -print0)

  # Loop through files to find _aflymake.go files and their base names
  local base_files=()
  for file in "${files[@]}"; do
    case "$file" in
      *_aflymake.go)
        base_files+=("${file%_aflymake.go}.go")
        ;;
    esac
  done

  # Exclude files corresponding to _aflymake.go files
  local final_list=()
  for file in "${files[@]}"; do
    local exclude=false
    for base_file in "${base_files[@]}"; do
      if [ "$file" = "$base_file" ]; then
        exclude=true
        break
      fi
    done
    if [ "$exclude" = false ]; then
      final_list+=("$file")
    fi
  done

  # Print the final list of files
  for file in "${final_list[@]}"; do
    echo "$file"
  done
}

if [ "$1" = "--fix" ]; then
  shift
  DO_GOFMT=1
fi

if [ -z "$1" ]; then
  log_info "Lint current dir '$(pwd)'..."
  if [ "$DO_GOFMT" = 1 ]; then
    (
      set -x
      go fmt
    )
  fi
  (
    set -x
    go build
  )
elif [ -d "$1" ]; then
  log_info "Lint dir '$(abspath "$1")'..."
  if [ "$DO_GOFMT" = 1 ]; then
    (
      set -x
      cd "$1"
      go fmt .
    )
  fi
  (
    set -x
    cd "$1"
    go build .
  )
else
  DIR=$(dirname "$1")
  # cd in the directory so that we get error message that only contain the filename
  cd "$DIR"
  FILES=$(list_files_excluding_aflymake .)
  log_info "Lint file '$1'..."
  log_info "(in directory '$(pwd)')"
  if [ "$DO_GOFMT" = 1 ]; then
    (
      set -x
      # shellcheck disable=SC2068
      go fmt ${FILES[@]}
    )
  fi
  (
    set -x
    # shellcheck disable=SC2068
    go build ${FILES[@]}
  )
fi
