#!/bin/bash -e
. ham-bash-lib.sh
if [ ! -e "venv/bin/activate" ]; then
    PY3_VENV_REQUIREMENTS_SHOULD_INSTALL=yes
    if [ ! -e "py3_requirements.txt" ]; then
        die "No venv and no py3_requirements.txt present to initialize it. You can use 'echo \"\" > py3_requirements.txt' to initialize an empty one."
    fi
    py3-venv "venv"
fi

source ./venv/bin/activate

if [ "$PY3_VENV_REQUIREMENTS_SHOULD_INSTALL" == "yes" ]; then
    py3-venv-requirements-install
    unset PY3_VENV_REQUIREMENTS_SHOULD_INSTALL
fi
