#!/bin/bash -e
usage() {
  echo "usage: git-status (head|short|short_log|full|diff|tui)"
  echo ""
  echo "  Default to 'short' if no mode is specified."
  exit 1
}

. "$HAM_HOME/bin/ham-bash-setenv.sh"

MODE="${1:-short_log}"
if [[ "$MODE" == "full" ]]; then
  git status
elif [[ "$MODE" == "short" ]]; then
  FORMAT=(--pretty=format:'%C(yellow)%h%Cgreen%d %Creset%s (%Cblue%an%Creset - %Cred%ad%Creset)' --date=short)
  git-head-info branch_changes
  git status -s
elif [[ "$MODE" == "short_log" ]]; then
  FORMAT=(--pretty=format:'%C(yellow)%h%Cgreen%d %Creset%s (%Cblue%an%Creset - %Cred%ad%Creset)' --date=short)
  git-head-info branch_changes
  git --no-pager log --decorate --oneline -3 --graph "${FORMAT[@]}"
  echo ""
  git status -s
elif [[ "$MODE" == "head" ]]; then
  git-head-info branch_changes
elif [[ "$MODE" == "diff" ]]; then
  log_info "=== Status Diffs ==="
  git --no-pager diff
  log_info "=== Status Summary ==="
  git-head-info branch_changes
  git status -s
elif [[ "$MODE" == "tui" ]]; then
  STATUS=$(git status -s)
  if [ -z "$STATUS" ]; then
    log_info "No changes"
    git-head-info branch_changes
  else
    git-tui
  fi
else
  log_error "Unknown mode '$MODE'."
  usage
fi
