#!/bin/bash -e
. ham-bash-lib.sh

usage() {
  echo "usage: git-push (origin) BRANCH"
  echo ""
  echo "  Safely force push the specified branch."
  if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    # sourced...
    return 1
  else
    # regular call
    exit 1
  fi
}

if [ -z "$1" ]; then
  usage
fi

REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")
trap 'log_error "Repo '"'"'$REPO_NAME'"'"' git-push failed."' ERR

if [ $# = 1 ]; then
  ORIGIN=origin
  BRANCH=$1
else
  ORIGIN=$1
  BRANCH=$2
fi

BRANCH=$(git-get-branch-name "$BRANCH")

log_info "Status"
git-status short
log_info "Pushing branch '$BRANCH' of '$REPO_NAME'."
(
  set -x
  git push --force-with-lease "$ORIGIN" "$BRANCH"
)
log_success "Repo '$REPO_NAME' git-push succeeded."
