#!/bin/bash
. "$HAM_HOME/bin/ham-bash-setenv.sh"

usage() {
  echo "usage: ${0##*/} BRANCH_NAME(usually main_branch) ORIGIN(default:origin)"
  echo ""
  echo "  Move the BRANCH_NAME branch to the current HEAD (that's the currently checked out branch),"
  echo "  then checkout BRANCH_NAME and finally push it to origin."
  echo ""
  exit 1
}

if [ -z "$1" ]; then
  echo "E/No branch name specified."
  usage
fi

BRANCH_NAME=$(git-check-branch-or-commit "$1")
if [ $? == 1 ]; then
  echo "E/Can't find branch '$1'."
  usage
fi

ORIGIN=${2:-origin}

ORIGIN_BRANCH_NAME=$(git-check-branch-or-commit "${ORIGIN}:${BRANCH_NAME}")
if [ $? == 1 ]; then
  echo "E/Can't get origin branch name '${ORIGIN}:${BRANCH_NAME}'."
  usage
fi

(
  set -ex
  git-move-branch "$BRANCH_NAME" HEAD
  git checkout "$BRANCH_NAME"
  git push "$ORIGIN"
)
