#!/bin/bash -e
export HAM_NO_VER_CHECK=1
. "$HAM_HOME/bin/ham-toolset" java_jdk >/dev/null
toolset_check_and_dl_ver repos jars v1 || return 1

# Examples:
#
# Delete everything except current main branch:
#   git-bfg --private --delete-files '*' --protect-blobs-from main
#   git-bfg --delete-files '*' --protect-blobs-from main
#

(
  set -x
  java -jar "${HAM_HOME}/toolsets/repos/jars/bfg-1.12.3.jar" "$@"
)
