#!/bin/bash -e
usage() {
  echo "usage: git-status (head|short|full|diff)"
  echo ""
  echo "  Default to 'short' if no mode is specified."
  exit 1
}

. "$HAM_HOME/bin/ham-bash-setenv.sh"

MODE="${1:-short}"
if [[ "$MODE" == "full" ]]; then
  git status
elif [[ "$MODE" == "short" ]]; then
  git-head-info branch_changes
  git status -s
elif [[ "$MODE" == "head" ]]; then
  git-head-info branch_changes
elif [[ "$MODE" == "diff" ]]; then
  echo "I/=== Status Diffs ==="
  git --no-pager diff
  echo "I/=== Status Summary ==="
  git-head-info branch_changes
  git status -s
else
  echo "E/Unknown mode '$MODE'."
  usage
fi
