#!/bin/bash
# Print a complete git log with a graph
. "$HAM_HOME/bin/ham-bash-setenv.sh"
git log --graph --abbrev-commit --decorate --format=format:'%C(bold red)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n'' %C(white)%s%C(reset) %C(yellow)- %an%C(reset)' --all
