#!/bin/bash
usage() {
    echo "usage: git-remotes ls"
    echo ""
    echo "  List all git remotes."
    echo ""
    echo "usage: git-remotes (regular git arguments)"
    echo ""
    echo "  Execute the specified git command for all remotes,"
    echo "  replacing __REMOTE__ by the remote name."
    exit 1
}

if [ -z "$1" ]; then
  usage
fi

if [ "$1" == "ls" ]; then
    shift
    git remote -v
else
    for REMOTE in `git remote`; do
        ARGS="${@/__REMOTE__/$REMOTE}"
        (set -x ; git $ARGS)
    done
fi
