#!/bin/bash
. ham-bash-lib.sh

help() {
  echo "usage: git-rebase branch_name"
  echo ""
  echo "  Rebase on the specified branch."
  exit 1
}
if [ -z "$1" ]; then
  help
fi

BRANCH=$(git-get-branch-name "$1")
shift

GIT_VERSION=$(git --version | grep -o '[0-9.]*')
MIN_VERSION="2.38"

version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

GIT_PARAMS=(--autostash)
# Add update-refs if possible. (see https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/)
if version_gt "$GIT_VERSION" "$MIN_VERSION"; then
  GIT_PARAMS=(--update-refs "${GIT_PARAMS[@]}")
else
  log_warning "git-rebase: not using update-refs as git version is too old."
fi

log_info "git-rebase: Rebasing on '$BRANCH'."
git rebase "${GIT_PARAMS[@]}" "$BRANCH" "$@"
log_info "git-rebase: Done."
