#!/bin/bash
help() {
    echo "usage: git-merge-rebase branch_name"
    echo ""
    echo "  Rebase the specified branch onto the current branch and then merges into it."
    echo ""
    exit 1
}
if [ -z "$1" ]; then
   help
fi

CURRENT_BRANCH=`git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
if [ -z "$1" ]; then
    echo "E/No branch name specified."
    help
fi

if [ ! -z "$(git status --porcelain)" ]; then
    echo "E/Changes detected, stash your changes before merging."
    help
fi

echo "I/Current Branch: $CURRENT_BRANCH"
echo "I/Merging: $1"

set -ex

git checkout "$1"
git rebase "$CURRENT_BRANCH"
git checkout "$CURRENT_BRANCH"
git merge --ff-only "$1"
