#!/bin/bash -e
for BRANCH in $(git branch -a | grep remotes | grep -v HEAD | grep -v master); do
  echo "I/Tracking branch ${BRANCH}"
  (
    set -x
    git branch --track ${BRANCH#remotes/origin/} ${BRANCH}
  )
done
