#!/bin/bash
help() {
  echo "usage: git-rebase branch_name"
  echo ""
  echo "  Rebase on the specified branch."
  exit 1
}
if [ -z "$1" ]; then
  help
fi

BRANCH=$(git-get-branch-name "$1")
shift

echo "I/Rebasing on '$BRANCH'."
git rebase --autostash "$BRANCH" "$@"
