#!/bin/bash -e
. ham-bash-lib.sh

help() {
  echo "usage: git-ensure-branch (nofetch) BRANCH (REMOTE_NAME)"
  echo ""
  echo "  If BRANCH exists locally or remotely, updates it using git-update"
  echo "  and then git-rebase it on main_branch. Otherwise creates a new"
  echo "  branch using git-new-branch."
  echo ""
  exit 1
}

DO_FETCH=1
if [ "$1" = "nofetch" ]; then
  shift
  DO_FETCH=0
fi

if [ -z "$1" ]; then
  help
fi

if [[ "$1" == "master" || "$1" == "main" ]]; then
  log_error "Cannot be used 'master' or 'main' as BRANCH, use 'main_branch' if you want to switch to the main or master branch so that we can detect which one your repo is actually using."
  help
fi

BRANCH=$(git-get-branch-name "$1")
REMOTE_NAME="${2:-origin}"

if [ "$DO_FETCH" = "1" ]; then
  (
    set -x
    git fetch --prune --all
  )
fi

if git rev-parse --verify "$BRANCH" >/dev/null 2>&1 ||
  git rev-parse --verify "$REMOTE_NAME/$BRANCH" >/dev/null 2>&1; then
  (
    set -x
    git-update nofetch "$BRANCH"
    git-rebase main_branch
  )
else
  (
    set -x
    git-new-branch nofetch "$BRANCH" "$REMOTE_NAME"
  )
fi
