#!/bin/bash
help() {
    echo "usage: git-remotes ls|regular git args"
    echo ""
    echo "  Execute the specified git command for all remotes,"
    echo "  replacing __REMOTE__ by the remote name."
    exit 1
}
if [ "$1" = "ls" ]; then
    shift
    for REMOTE in `git remote`; do
        ARGS="${@/__REMOTE__/$REMOTE}"
        # echo "Runing: $CMD $ARGS"
        echo $REMOTE: $ARGS
    done
else
    for REMOTE in `git remote`; do
        ARGS="${@/__REMOTE__/$REMOTE}"
        (set -x ; git $ARGS)
    done
fi
