#!/bin/bash
# see: https://git-scm.com/docs/pretty-formats
if [ "$1" == "json" ]; then
    TZ=UTC git show --date=iso-local --quiet HEAD --pretty=format:"{\"hash\":\"%h\", \"author\":\"%cn\", \"commit date\":\"%cd\", \"commit subject\":\"%s\", \"branch\":\"%D\"}"
else
    TZ=UTC git show --date=iso-local --quiet HEAD --pretty=format:"- hash: %h%n- author: \"%cn\"%n- commitDate: \"%cd\"%n- commitSubject:\"%s\"%n- branch: \"%D\"%n"
fi
