#!/bin/bash
HEAD_HASH=`git show --quiet HEAD --pretty=format:"%h"`
HEAD_TIMESTAMP=`git show --quiet HEAD --pretty=format:"%ct"`
HEAD_DATE_UTC_FILE=`date -u -r $HEAD_TIMESTAMP +"%Y%m%d_%H%M%SZ"`
HEAD_DATE_UTC_ISO=`date -u -r $HEAD_TIMESTAMP +"%Y-%m-%dT%H:%M:%SZ"`
CURRENT_BRANCH=`git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
TAG=`echo ${HEAD_DATE_UTC_FILE}_${CURRENT_BRANCH}_${HEAD_HASH}`

# see: https://git-scm.com/docs/pretty-formats
if [ "$1" == "json" ]; then
    TZ=UTC git show --date=iso-local --quiet HEAD --pretty=format:"{\"hash\":\"${TAG}\", \"hash\":\"%h\", \"author\":\"%cn\", \"commit date\":\"${HEAD_DATE_UTC_ISO}\", \"commit subject\":\"%s\", \"branch\":\"${CURRENT_BRANCH}\"}"
else
    TZ=UTC git show --date=iso-local --quiet HEAD --pretty=format:"- tag: ${TAG}%n- hash: %h%n- author: \"%cn\"%n- commitDate: \"${HEAD_DATE_UTC_ISO}\"%n- commitSubject:\"%s\"%n- branch: ${CURRENT_BRANCH}%n"
fi
