#!/bin/bash
. "$HAM_HOME/bin/ham-bash-setenv.sh"

GIT_BATCH_DEFAULT_REMOTE=origin

# the help
usage() {
    echo "usage: git-batch [ commands ]"
    echo ""
    echo "  Runs the specified git commands in the specified order."
    echo "  Stops at the first failure."
    echo ""
    echo "commands:"
    echo "  -h             This help message"
    echo "  -d             Fetch all branches (download) from '$GIT_BATCH_DEFAULT_REMOTE' remote"
    echo "  -D remote      Fetch all branches (download) from the specified remote"
    echo "  -f             Fetch all branches (download) from all remotes"
    echo "  -l             Print the last 4 commit messages"
    echo "  -L count       Print the last 'count' commit messages"
    echo "  -m             Fetch & merge (pull) from '$GIT_BATCH_DEFAULT_REMOTE' to 'current branch'"
    echo "  -M remote      Fetch & merge (pull) from the specified remote to 'current branch'"
    echo "  -p             Push to '$GIT_BATCH_DEFAULT_REMOTE'"
    echo "  -P remote      Push to the specified remote"
    echo "  -u             Push all (upload) to '$GIT_BATCH_DEFAULT_REMOTE'"
    echo "  -U remote      Push all (upload) to the specified remote"
    echo "  -t             Push all tags (upload) to '$GIT_BATCH_DEFAULT_REMOTE'"
    echo "  -T remote      Push all tags (upload) to the specified remote"
    echo "  -s             Status of the repo"
    echo "  -y             Fetch all from '$GIT_BATCH_DEFAULT_REMOTE', merge '$GIT_BATCH_DEFAULT_REMOTE' into 'current branch',"
    echo "                 then push all to '$GIT_BATCH_DEFAULT_REMOTE'. Alias for '-f -m -u -t'."
    echo ""
    echo "example:"
    echo "  # fetch all from '$GIT_BATCH_DEFAULT_REMOTE', merge '$GIT_BATCH_DEFAULT_REMOTE' into 'current branch',"
    echo "  # then push all to '$GIT_BATCH_DEFAULT_REMOTE'"
    echo "  git-batch -f -m -u"
    echo "  # fetch all from '$GIT_BATCH_DEFAULT_REMOTE', merge '$GIT_BATCH_DEFAULT_REMOTE' into 'current branch',"
    echo "  # then push all to '$GIT_BATCH_DEFAULT_REMOTE'"
    echo "  git-batch -y"
    echo "  # fetch all from '$GIT_BATCH_DEFAULT_REMOTE', merge '$GIT_BATCH_DEFAULT_REMOTE' into 'current branch',"
    echo "  # then push all to '$GIT_BATCH_DEFAULT_REMOTE' and to 'bonobo'"
    echo "  git-batch -f -m -u -U bonobo"
    echo ""

    if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
        # sourced...
        return 1
    else
        # regular call
        exit 1
    fi
}

# Check that there is at least one argument...
if [ $# = 0 ]; then
    echo "E/No argument specified"
    echo ""
    usage
fi

if [ -z "$GITK_CMD" ]; then
    GITK_CMD=gitk
fi

# process the arguments
while getopts "dD:eE:fhlL:mM:pP:uU:tT:sSyk" OPT
do

    CMD=
    case "$OPT" in
        h)
            usage
            ;;
        \?)
            usage
            ;;
        s)
            CMD="git status --porcelain"
            ;;
        S)
            CMD="git status"
            ;;
        d)
            CMD="git fetch --prune $GIT_BATCH_DEFAULT_REMOTE"
            ;;
        D)
            CMD="git fetch --prune $OPTARG"
            ;;
        f)
            CMD="git fetch --prune --all"
            ;;
        l)
            CMD="git log -4 --pretty=oneline --abbrev-commit"
            ;;
        L)
            CMD="git log -${OPTARG} --pretty=oneline --abbrev-commit"
            ;;
        p)
            CMD="git push $GIT_BATCH_DEFAULT_REMOTE"
            ;;
        P)
            CMD="git push $OPTARG"
            ;;
        u)
            CMD="git push --all $GIT_BATCH_DEFAULT_REMOTE"
            ;;
        U)
            CMD="git push --all $OPTARG"
            ;;
        t)
            CMD="git push --tags $GIT_BATCH_DEFAULT_REMOTE"
            ;;
        T)
            CMD="git push --tags $OPTARG"
            ;;
        m)
            export GIT_CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
            CMD="git pull --ff-only origin ${GIT_CURRENT_BRANCH}"
            ;;
        M)
            export GIT_CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
            CMD="git pull --ff-only $OPTARG ${GIT_CURRENT_BRANCH}"
            ;;
        y)
            CMD="git-batch -f -m -u -t"
            ;;
        k)
            HAS_CHANGES=`git status --porcelain`
            if [ ! -z "$HAS_CHANGES" ]; then
                CMD="\"$GITK_CMD\""
            fi
            ;;
        K)
            CMD="\"$GITK_CMD\""
            ;;
    esac

    if [ -z "$CMD" ]; then
        echo "I/Skipped `pwd`"
    else
        echo "I/$CMD (in `pwd`)"
        eval $CMD
        errcheck $? git_batch "git-batch error: $CMD (in `pwd`)"
    fi

done
