#!/bin/bash -e
usage() {
    echo "usage: git-gui DIRECTORY (default to .)"
    echo ""
    echo "  Open the first available Git GUI with the specified directory."
    echo ""
    echo "  Trying in this order:"
    echo "    $GIT_GUI"
    echo "  When not in SSH session:"
    echo "    fork (https://git-fork.com/)"
    echo "    smerge (https://www.sublimemerge.com/)"
    echo "  Command line / TUI:"
    echo "    lazygit"
    exit 1
}

DIR=${1:-.}
if [ ! -d "$DIR" ]; then
    echo "E/Can't find directory '$DIR'."
    usage
fi

if [ -z "$GIT_GUI" ]; then
    # Check GUI for a windowed mode
    if [ `where_inpath fork` ]; then
        GIT_GUI=fork
    elif [ `where_inpath smerge` ]; then
        # sudo ln -s "/Applications/Sublime Merge.app/Contents/SharedSupport/bin/smerge" /usr/local/bin/smerge
        GIT_GUI=smerge
    elif [ `where_inpath gitk` ]; then
        GIT_GUI=gitk
    fi

    # If we didnt a find a windowed GUI or we're in a SSH session try the
    # TUI's
    if [ -z "$GIT_GUI" ] || [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]
    then
        echo "I/In SSH session, picking a TUI git client."
        if [ `where_inpath lazygit` ]; then
            GIT_GUI=lazygit
        fi
    fi
fi

if [ -z "$GIT_GUI" ] || [ -z `where_inpath "$GIT_GUI"` ]; then
    echo "E/Can't find GUI_GUI_CMD '$GIT_GUI'."
    usage
fi

(set -x ; "$GIT_GUI" "$DIR")
