#!/bin/bash -e
. "$HAM_HOME/bin/ham-bash-setenv.sh"

usage() {
    echo "usage: ${0##*/} BRANCH_NAME(usually main or master) ORIGIN(default:origin)"
    echo ""
    echo "  Move the BRANCH_NAME branch to the current HEAD (that's the currently checked out branch),"
    echo "  then checkout BRANCH_NAME and finally push it to origin."
    echo ""
    exit 1
}

if [ -z "$1" ]; then
    echo "E/No branch name specified."
    usage
fi
BRANCH_NAME=$1
shift

if [ -n "$2" ]; then
  ORIGIN=$2
  shift
else
  ORIGIN=origin
fi

echo "I/Fetching and rebasing on '$ORIGIN/$BRANCH_NAME'"
(set -x ;
 git fetch --all ;
 git-rebase $ORIGIN/$BRANCH_NAME)

echo "I/Moving '$BRANCH_NAME' to HEAD"
(set -x ;
 git push $ORIGIN --force-with-lease ;
 git-move-branch-to-head $BRANCH_NAME)

echo "I/Checking out '$BRANCH_NAME' and pushing to '$ORIGIN'"
(set -x ;
 git checkout $BRANCH_NAME ;
 git push $ORIGIN)
