#!/bin/bash -e
. "$HAM_HOME/bin/ham-bash-setenv.sh"

usage() {
  echo "usage: ${0##*/} (nostash)"
  echo ""
  echo "  'ham-gt downstack get' with auto stashing and restacking."
  exit 1
}

STASH=1
if [ "$1" == "nostash" ]; then
  STASH=0
  shift
fi

if [ $STASH == 1 ]; then
  (
    set -x
    git-stash trypop gt-get
    git-stash push gt-get
  )
fi

(
  set -x
  ham-gt dsg $@
  ham-gt stack restack
)

if [ $STASH == 1 ]; then
  (
    set -x
    git-stash trypop gt-get
  )
fi
