#!/bin/bash -e
. "$HAM_HOME/bin/ham-bash-setenv.sh"
export HAM_NO_VER_CHECK=1
toolset_import_once nodejs > /dev/null

usage() {
    echo "usage: ${0##*/}"
    echo ""
    echo "  'gt ls' list the current branches and display their stack."
    exit 1
}

(set -x;
 gt ls)
