#!/bin/bash -e
. "$HAM_HOME/bin/ham-bash-setenv.sh"
export HAM_NO_VER_CHECK=1
toolset_import_once nodejs > /dev/null

usage() {
    echo "usage: ${0##*/} BRANCH_NAME(usually main or master) ORIGIN(default:origin)"
    echo ""
    echo "  Move the BRANCH_NAME branch to the current HEAD (that's the currently checked out branch),"
    echo "  then checkout BRANCH_NAME, push it to origin and finally run gt-sync."
    echo ""
    echo "  The intended flow to merge a stack is to checkout the branch at the bottom of"
    echo "  the stack with 'gt-co-branch' and then run 'gt-merge-current-branch main/master'."
    echo "  That will move 'main/master' to the current branch, push it to the origin and then"
    echo "  run 'gt-sync'. Once finished the process can be repeated with the next branch in"
    echo "  the stack until they are all merged."
    echo ""
    exit 1
}

if [ -z "$1" ]; then
    echo "E/No branch name specified."
    usage
fi
BRANCH_NAME=$1
shift

if [ -n "$2" ]; then
  ORIGIN=$2
  shift
else
  ORIGIN=origin
fi

(set -x ;
 git-move-branch-to-head $BRANCH_NAME ;
 git checkout $BRANCH_NAME ;
 git push $ORIGIN ;
 gt-sync)
