#!/bin/bash -e
. "$HAM_HOME/bin/ham-bash-setenv.sh"

usage() {
    echo "usage: ${0##*/} BASE_BRANCH_NAME"
    echo ""
    echo "  Create a branch with 'git-new-branch' and then track it with 'gt branch track'. Prefix the branch name with '$USER-%y-%m-%d'."
    echo ""
    exit 1
}

if [ -z "$1" ]; then
    echo "E/No BASE_BRANCH_NAME specified."
    usage
fi

(set -x ;
 BRANCH_PREFIX=$(date +"$USER-%y-%m-%d") ;
 git-new-branch "$BRANCH_PREFIX-$1" ;
 ham-gt branch track "$BRANCH_PREFIX-$1")
