#!/bin/bash -e
usage() {
    echo "usage: ${0##*/} (nostash)"
    echo ""
    echo "  'gt stack restack' with auto stashing."
    exit 1
}

STASH=1
if [ "$1" == "nostash" ]; then
    STASH=0
    shift
fi

if [ $STASH == 1 ]; then
  (set -x;
   git-stash trypop gt-restack ;
   git-stash push gt-restack)
fi

(set -x;
 gt stack restack)

if [ $STASH == 1 ]; then
    (set -x ;
     git-stash trypop gt-restack)
fi
