#!/bin/bash -e
. "$HAM_HOME/bin/ham-bash-setenv.sh"

usage() {
    echo "usage: ${0##*/} (nostash)"
    echo ""
    echo "  'ham-gt repo sync --restack' with auto stashing."
    exit 1
}

STASH=1
if [ "$1" == "nostash" ]; then
    STASH=0
    shift
fi

if [ $STASH == 1 ]; then
  (set -x;
   git-stash trypop gt-sync ;
   git-stash push gt-sync)
fi

(set -x; ham-gt repo sync --restack --show-delete-progress --delete --force)

if [ $STASH == 1 ]; then
    (set -x ;
     git-stash trypop gt-sync)
fi
