#!/bin/bash -e
. "$HAM_HOME/bin/ham-bash-setenv.sh"

usage() {
    echo "usage: ${0##*/} BRANCH_NAME"
    echo ""
    echo "  'ham-gt upstack onto' Rebase the current branch onto the latest commit of the"
    echo "  target branch and restack all of its descendants. If no branch is passed in,"
    echo "  opens an interactive selector."
    exit 1
}

if [ -z "$1" ]; then
  echo "E/BRANCH_NAME not specified."
  usage
fi

(set -x ;
 ham-gt upstack onto "$@")
