#!/bin/bash
. ham-bash-lib.sh

echo "########################################################################"
echo "## Status"
echo "########################################################################"
repos git status 2>&1 | tee ~/_repos-maintain-report-status.txt

echo "########################################################################"
echo "## Fetch All"
echo "########################################################################"
repos git fetch --tags
repos git fetch --all 2>&1 | tee ~/_repos-maintain-report-fetch-all.txt

echo "########################################################################"
echo "## Pull origin master"
echo "########################################################################"
repos git pull origin master 2>&1 | tee ~/_repos-maintain-report-pull-origin-master.txt

echo "########################################################################"
echo "## Push all"
echo "########################################################################"
repos git push --tags
repos git push --all 2>&1 | tee ~/_repos-maintain-report-push-all.txt

echo "########################################################################"
echo "## Done !"
echo "########################################################################"
