#!/bin/bash -e
if [[ -z $HAM_PROJECT_DIR ]]; then
    echo "E/HAM_PROJECT_DIR not set !"
    return 1
fi

if [ ! -d "github-thrift" ]; then
  toolset_import_list repos || return 1
  (set -x ; git clone --depth 10 https://github.com/bytecollider/thrift.git github-thrift)
else
  echo "I/cppm-thrift: github-thrift already cloned"
fi

toolset_import_list repos cppm boost_cppm || return 1
