#!/bin/bash -e
if [[ -z $HAM_PROJECT_DIR ]]; then
    echo "E/HAM_PROJECT_DIR not set !"
    return 1
fi

if [ ! -d "github-thrift" ]; then
  toolset_import_list repos || return 1
  (set -x ; git clone --depth 1 https://github.com/bytecollider/thrift.git github-thrift)
else
  echo "I/cppm-thrift: github-thrift already cloned"
fi

export BUILD=${BUILD:-ra}
export BUILD_TARGET=${BUILD_TARGET:-default}

CPP_TOOLSET=$(ham-cppm-get-toolset "${BUILD_TARGET}")
retcheck $? "Can't get C++ toolset for BUILD_TARGET '$BUILD_TARGET'." || return 1

case $HAM_OS in
    LINUX*|OSX*)
        toolset_import_list repos openssl $CPP_TOOLSET boost_cppm || return 1
        ;;
    *)
        toolset_import_list repos $CPP_TOOLSET boost_cppm || return 1
        ;;
esac
