#!/bin/bash
case $HAM_OS in
    NT*)
        ;;
    *)
        echo "E/Toolset: Unsupported host OS"
        exit 1
        ;;
esac
echo "# Stopping MySQL service..."
net stop ts_mysql
echo "# Removing MySQL service..."
mysqld --remove ts_mysql
