#!/bin/bash
case $HAM_OS in
    NT*)
        ;;
    *)
        echo "E/Toolset: Unsupported host OS"
        exit 1
        ;;
esac
if [ ! -e "$MYSQL_DB_DIR/data/mysql/db.MYD" ]; then
    mysql_initdb
fi
mysql_run
