#!/bin/bash
case $HAM_OS in
    NT*)
        ;;
    *)
        echo "E/Toolset: Unsupported host OS"
        exit 1
        ;;
esac
if [ ! -e "$MYSQL_DB_DIR/data/mysql/db.MYD" ]; then
    mysql_initdb
fi
echo "# Installing MySQL service..."
mysqld --install ts_mysql --defaults-file="$MYSQL_DB_DIR/my.cnf" "$@"
echo "# Starting MySQL service..."
net start ts_mysql
