#!/bin/bash
#
# See:
# - https://trac.ffmpeg.org/wiki/Waveform
# - https://stackoverflow.com/questions/32254818/generating-a-waveform-using-ffmpeg
#
. ham-bash-lib.sh
SRC="$1"
DST="$2"
RES="${3:-512x128}"
if [ -z "$DST" ]; then
  DST="${SRC}.thumb.png"
fi
set -ex

# Basic
basic_waveform() {
  ffmpeg -i "$SRC" \
    -f lavfi -i color=c=black:s=$RES -filter_complex "[0:a]compand,showwavespic=s=$RES:colors=white[fg];[1:v][fg]overlay=format=auto" \
    -frames:v 1 "$DST"
}

fancy_waveform() {
  ffmpeg -i "$SRC" -filter_complex \
    "[0:a]aformat=channel_layouts=mono, \
 compand=gain=-6, \
 showwavespic=s=$RES:colors=#9cf42f[fg]; \
 color=s=$RES:color=#44582c, \
 drawgrid=width=iw/10:height=ih/5:color=#9cf42f@0.1[bg]; \
 [bg][fg]overlay=format=auto,drawbox=x=(iw-w)/2:y=(ih-h)/2:w=iw:h=1:color=#9cf42f" \
    -frames:v 1 "$DST"
}

fancy_waveform
