#!/bin/bash

#
# Example use with xargs:
#   find . -name "*.wav" | xargs -n1 -P 20 ffmpeg_remove_begin_end_silence
#

. ham-bash-lib.sh
SRC="$1"
DST="$2"
if [ -z "$DST" ]; then
  DST="${SRC%.*}_nosilence.wav"
fi
set -ex
ffmpeg -i "${SRC}" -af "silenceremove=start_periods=1:start_silence=0.1:start_threshold=-50dB,areverse,silenceremove=start_periods=1:start_silence=0.1:start_threshold=-50dB,areverse" "$DST"
