#!/bin/bash -e
. ham-bash-lib.sh

if [ "$1" = "force" ]; then
  shift
  echo "I/npm-install-global-deps: Forcing the installation of the required node modules."
elif [ ! -e "${NODEJS_BIN_DIR}/eslint" ] ||
  [ ! -e "${NODEJS_BIN_DIR}/gulp" ] ||
  [ ! -e "${NODEJS_BIN_DIR}/jsonlint" ] ||
  [ ! -e "${NODEJS_BIN_DIR}/node-pre-gyp" ] ||
  [ ! -e "${NODEJS_BIN_DIR}/esbuild" ] ||
  [ ! -e "${NODEJS_BIN_DIR}/yarn" ] ||
  [ ! -e "${NODEJS_BIN_DIR}/pm2" ] ||
  [ ! -e "${NODEJS_BIN_DIR}/gt" ] ||
  [ ! -e "${NODEJS_BIN_DIR}/browserify" ]; then
  echo "I/npm-install-global-deps: Not all required packages are installed"
else
  echo "I/npm-install-global-deps: All required global packages are installed."
  exit 0
fi

# Make sure we're not in a place where there's a package.json that could
# confuse `npm install -g`
cd "$HAM_HOME"

echo "I/Installing packages with scripts..."
npm install --force -g \
  eslint@8.x \
  gulp@3.x \
  jsonlint \
  node-pre-gyp \
  esbuild \
  yarn \
  pm2 \
  @withgraphite/graphite-cli \
  browserify

echo "I/Installing regular packages..."
npm install --force -g --no-bin-links \
  css-loader@0.15.x \
  eslint-plugin-react@7.x \
  eslint-plugin-promise@6.x \
  extract-text-webpack-plugin@0.8.x \
  file-loader@0.8.x \
  jsx-loader@0.13.x \
  less-loader@2.2.x \
  less@2.5.x \
  mocha@2.2.x \
  nodemon@1.3.7 \  react-hot-loader@1.2.x \
  react-script-loader@0.0.1 \
  react-tools@0.13.x \
  script-loader@0.6.x \
  style-loader@0.12.x \
  supertest@1.x \
  url-loader@0.5.x \
  webpack-dev-server@1.x \
  webpack@1.x

# echo "I/Installed global packages:"
# (set -x ;
#  npm root -g
#  npm list -g --depth=0)
