#!/bin/bash
. ham-bash-lib.sh

case $HAM_OS in
    NT*)
        TSC="${HAM_HOME}/toolsets/nodejs/nt-x86/tsc"
        ;;
    OSX*)
        TSC="${HAM_HOME}/toolsets/nodejs/osx-x86/bin/tsc"
        ;;
    *)
        echo "E/Toolset: Unsupported host OS"
        exit 1
        ;;
esac
${TSC} --module commonjs --noEmit "$@" && echo "TypeScript Lint: No Errors."
