#!/bin/bash

#
# Example of _lint.sh that uses yarn to run eslint. Copy as _lint.sh the root
# of your project, or one of its parent folder.
#

export HAM_NO_VER_CHECK=1
if [[ -z "$HAM_HOME" ]]; then echo "E/HAM_HOME not set !"; exit 1; fi
. "$HAM_HOME/bin/ham-bash-setenv.sh"

. ham-toolset nodejs > /dev/null

yarn run eslint "$@"
