#!/bin/bash
# textedit_dir DIRECTORY FILE
. ham-bash-lib.sh
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
case $HAM_OS in
  NT*)
    "${DIR}/nt-x86/SciTE.exe" -check.if.already.open=1 "$2" &
    ;;
  OSX*)
    SUBLIME_APP="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
    if [[ -e "$SUBLIME_APP" ]]; then
      "$SUBLIME_APP" "$2"
    else
      open -e "$2"
    fi
    ;;
  *)
    echo "E/Toolset: Unsupported host OS"
    return 1
    ;;
esac
