#!/bin/bash
. ham-bash-lib.sh
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
case $HAM_OS in
  NT*)
    "${DIR}/nt-x86/SciTE.exe" -check.if.already.open=1 "$@" &
    ;;
  OSX*)
    open -e "$@"
    ;;
  *)
    echo "E/Toolset: Unsupported host OS"
    return 1
    ;;
esac
