#
# See https://alacritty.org/config-alacritty.html
#
# Run alacritty in a shortcut:
#   c:\Utils\Alacritty.exe --config-file c:/Utils/alacritty-ham-shell.toml
#
# Run alacritty from bash:
#   ./Alacritty.exe --config-file /c/Utils/alacritty-ham-shell.toml
#

# live_config_reload = true

import = [
"../config/alacritty-ui.toml",
"../config/alacritty-input.toml",
]

# [shell]
# program = "K:/Work/ham/toolsets/repos/nt-x86/git/bin/bash.exe"
# args = ["--rcfile", "C:/Utils/alacritty-ham-shell-start.sh", "-i"]
