[window]
dimensions = { columns = 88, lines = 40 }
padding = { x = 2, y = 2 }
startup_mode = "Windowed"
title = "ham-shell"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"
opacity = 1
blur = false

[scrolling]
history = 100000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[font]
normal.family = "Consolas"
bold.family = "Consolas"
italic.family = "Consolas"
bold_italic.family = "Consolas"
size = 11.0
