#!/bin/sh
. ham-bash-lib.sh

case $HAM_OS in
    NT*)
        ;;
    *)
        echo "E/Toolset: Unsupported host OS, this is for Windows only."
        exit 1
        ;;
esac

echo "# Setting up the Ruby toolchain to build native modules on Windows..."
export RUBY_DEVKIT_DIR="$RUBY_DIR/devkit"
if [ ! -e "$RUBY_DEVKIT_DIR" ]; then
    echo "E/Toolset: Could not find the ruby devkit folder, make sure the toolset has been downloaded correctly."
    exit 1
fi

echo "# Autogenerated config.yml" > "$RUBY_DEVKIT_DIR/config.yml"
echo "-" `nativedir "$RUBY_DIR"` >> "$RUBY_DEVKIT_DIR/config.yml"
echo "" >> "$RUBY_DEVKIT_DIR/config.yml"

cd "$RUBY_DEVKIT_DIR"
ruby dk.rb install -f

echo "# Done."
