name: run_ci

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Run on all push in main
  push:
    branches: [ main, master ]
  # Run on all pull requests
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu20:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Ubuntu packages
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt install -y clang curl ffmpeg freeglut3-dev g++ gcc git libcurl4-openssl-dev lftp libsdl2-dev libssl-dev libudev-dev mesa-common-dev mesa-utils ntpdate p7zip-full pkg-config python3 python3-pip subversion wget xsltproc libdw-dev libunwind-dev

      - name: Hat repos & default
        run: |
          source _env.sh
          . hat repos default

      - name: Run_ci
        run: |
          source _env.sh
          ./_run_ci.sh

  build_macos_latest:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Hat repos & default
        run: |
          source _env.sh
          . hat repos default

      - name: Run_ci
        run: |
          source _env.sh
          ./_run_ci.sh

  build_windows_latest:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run_ci
        run: |
          .\bin\ham.cmd -X ham _run_ci.sh
