name: run_ci

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Run on all push in main
  push:
    branches: [ main, master ]
  # Run on all pull requests
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu22:
    runs-on: ubuntu-22.04

    steps:
      # Check-out our repository
      - uses: actions/checkout@v3

      - name: Install OS packages
        run: |
          ./bin/ham-install-os-packages

      - name: ham-toolset repos svn default
        run: |
          ./bin/ham-toolset repos svn default

      - name: ham-toolset rclone python_3 nodejs php_8
        run: |
          ./bin/ham-toolset rclone python_3 nodejs php_8

      - name: _run_ci.sh
        run: |
          ./bin/ham -X ham _run_ci.sh

  build_ubuntu24:
    runs-on: ubuntu-24.04

    steps:
      # Check-out our repository
      - uses: actions/checkout@v3

      - name: Install OS packages
        run: |
          ./bin/ham-install-os-packages

      - name: ham-toolset repos svn default
        run: |
          ./bin/ham-toolset repos svn default

      - name: ham-toolset rclone python_3 nodejs php_8
        run: |
          ./bin/ham-toolset rclone python_3 nodejs php_8

      - name: _run_ci.sh
        run: |
          ./bin/ham -X ham _run_ci.sh

  build_macos_latest:
    runs-on: macos-latest

    steps:
      # Check-out our repository
      - uses: actions/checkout@v3

      - name: Install OS packages
        run: |
          ./bin/ham-install-os-packages

      - name: ham-toolset repos svn default
        run: |
          ./bin/ham-toolset repos svn default

      - name: ham-toolset rclone python_3 nodejs php_8
        run: |
          ./bin/ham-toolset rclone python_3 nodejs php_8

      - name: _run_ci.sh
        run: |
          ./bin/ham -X ham _run_ci.sh

  build_windows_latest:
    runs-on: windows-latest

    steps:
      - name: Turn off git eol insanity on Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      # Check-out our repository
      - uses: actions/checkout@v3

      - name: ham-install-for-windows
        run: |
          .\bin\ham-install-for-windows.cmd

      - name: ham-toolset repos svn default
        run: |
          .\bin\ham-toolset.cmd repos svn default

      - name: ham-toolset rclone python_3 nodejs php_8
        run: |
          .\bin\ham-toolset.cmd rclone python_3 nodejs php_8

      - name: _run_ci.sh
        run: |
          .\bin\ham.cmd -X ham _run_ci.sh
