name: run_ci

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Run on all push in main
  push:
    branches: [ main, master ]
  # Run on all pull requests
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu20:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Check-out our repository
      - uses: actions/checkout@v3

      - name: Install Ubuntu packages
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt install -y clang curl ffmpeg freeglut3-dev g++ gcc git libcurl4-openssl-dev lftp libsdl2-dev libssl-dev libudev-dev mesa-common-dev mesa-utils ntpdate p7zip-full pkg-config python3 python3-pip subversion wget xsltproc libdw-dev libunwind-dev

      - name: ham-toolset repos default
        run: |
          ./bin/ham-toolset repos default

      - name: ham-toolset rclone python_3 nodejs php_8
        run: |
          ./bin/ham-toolset rclone python_3 nodejs php_8

      - name: _run_ci.sh
        run: |
          ./bin/ham -X ham _run_ci.sh

  build_macos_latest:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Check-out our repository
      - uses: actions/checkout@v3

      - name: ham-toolset repos default
        run: |
          ./bin/ham-toolset repos default

      - name: ham-toolset rclone python_3 nodejs php_8
        run: |
          ./bin/ham-toolset rclone python_3 nodejs php_8

      - name: _run_ci.sh
        run: |
          ./bin/ham -X ham _run_ci.sh

  build_windows_latest:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: Turn off git eol insanity on Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      # Check-out our repository
      - uses: actions/checkout@v3

      - name: ham-install-for-windows
        run: |
          .\bin\ham-install-for-windows.cmd

      - name: ham-toolset repos default
        run: |
          .\bin\ham-toolset.cmd repos default

      - name: ham-toolset rclone python_3 nodejs php_8
        run: |
          .\bin\ham-toolset.cmd rclone python_3 nodejs php_8

      - name: _run_ci.sh
        run: |
          .\bin\ham.cmd -X ham _run_ci.sh
